steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$REPO_NAME:$COMMIT_SHA'
      - '.'

  # Step 2: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$REPO_NAME:$COMMIT_SHA'

  # Step 3: Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image=$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$REPO_NAME:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--platform=managed'

images:
  - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$REPO_NAME:$COMMIT_SHA'
